const express= require("express");
const userController=require('../controller/userController');
const notificationController=require('../controller/notificationController');
const contactController=require('../controller/contactController');
const subscriptionController=require('../controller/subscriptionController');
const subscriptionBuyController=require('../controller/subscriptionBuyController');
const AdminController=require('../controller/AdminController');
const{authentication}=require('../middleware/authentication');
const router=express.Router();
router.post('/signUp',userController.signUp);
router.post('/login',userController.login);
router.post('/OtpVerify',userController.OtpVerify);
router.post('/otpCheck',userController.otpCheck);
router.post('/notification',notificationController.notification);
router.post('/getnotification',authentication,notificationController.getnotification);
router.post('/Clearnotification',authentication,notificationController.Clearnotification);
router.post('/contactDetail',contactController.contactDetail);
router.post('/addShort',userController.addShort);
router.post('/addGoal',userController.addGoal);
router.post('/subscription',subscriptionController.subscription);
router.post('/subBuy',subscriptionBuyController.subBuy);
router.post('/clearShort',authentication,userController.clearShort);
router.post('/dosageStrength',AdminController.dosageStrength);
router.post('/Meditation',AdminController.Meditation);
router.post('/InjectionSite',AdminController.InjectionSite);
router.post('/clearGoal',authentication,userController.clearGoal);
router.post('/EditShort',userController.EditShort);
router.post('/EditGoal',userController.EditGoal);
router.post('/logout',authentication,userController.logout);
module.exports=router;