const express= require("express");
const userController=require('../controller/userController');
const notificationController=require('../controller/notificationController');
const contactController=require('../controller/contactController');
const subscriptionController=require('../controller/subscriptionController');
const subscriptionBuyController=require('../controller/subscriptionBuyController');
const AdminController=require('../controller/AdminController');
const{authentication}=require('../middleware/authentication');
const router=express.Router();
router.post('/signUp',userController.signUp);
router.post('/login',userController.login);
router.post('/OtpVerify',userController.OtpVerify);
router.post('/otpCheck',userController.otpCheck);
router.post('/notification',authentication,notificationController.notification);
router.post('/getnotification',authentication,notificationController.getnotification);
router.post('/Clearnotification',authentication,notificationController.Clearnotification);
router.post('/contactDetail',authentication,contactController.contactDetail);
router.post('/addShort',authentication,userController.addShort);
router.post('/addGoal',authentication,userController.addGoal);
router.post('/subscription',authentication,subscriptionController.subscription);
router.post('/subBuy',authentication,subscriptionBuyController.subBuy);
router.post('/clearShort',authentication,userController.clearShort);
router.post('/dosageStrength',authentication,AdminController.dosageStrength);
router.post('/Meditation',authentication,AdminController.Meditation);
router.post('/InjectionSite',authentication,AdminController.InjectionSite);
router.post('/clearGoal',authentication,userController.clearGoal);
router.post('/EditShort',authentication,userController.EditShort);
router.post('/EditGoal',authentication,userController.EditGoal);
router.post('/updateGoal',authentication,userController.updateGoal);
router.post('/updateShort',authentication,userController.updateShort);
router.post('/logout',authentication,userController.logout);
module.exports=router;